DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    ID        BIGINT auto_increment PRIMARY KEY,
    FIRSTNAME VARCHAR(255),
    SURNAME   VARCHAR(255)
);
DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE
(
    ID    BIGINT auto_increment PRIMARY KEY,
    TITLE VARCHAR(255)
);
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS
(
    ID        BIGINT auto_increment PRIMARY KEY,
    TITLE     VARCHAR(255),
    AUTHOR_ID BIGINT,
    GENRE_ID  BIGINT
);